Updates to the Dependencies Handling
microsoft/Microsoft365DSC pull request #1612
Opened 2021-12-03 20:25 UTC by NikCharlebois

#### Pull Request (PR) description
Added a new mechanism to handle dependencies and removed the required modules list from the main module's manifest.

#### This Pull Request (PR) fixes the following issues
N/A

2021-12-06 15:01 UTC, ykuijs commented on Modules/Microsoft365DSC/Modules/M365DSCLogEngine.psm1
> +    Confirm-M365DSCDependencies
Indentation inconsistent

2021-12-06 15:01 UTC, ykuijs commented on Modules/Microsoft365DSC/Modules/M365DSCReport.psm1
> +    Confirm-M365DSCDependencies
Indentation inconsistent

2021-12-06 17:31 UTC, NikCharlebois commented on Modules/Microsoft365DSC/DSCResources/MSFT_AADNamedLocationPolicy/MSFT_AADNamedLocationPolicy.psm1
> +    Confirm-M365DSCDependencies
Nope it's fixed now.

2021-12-06 23:28 UTC, NikCharlebois commented
@ykuijs all comments have been fixed, can you please review again and approve? Thanks

2021-12-07 11:17 UTC, ykuijs requested changes
Not all comments are updated

2021-12-07 11:17 UTC, ykuijs commented on Modules/Microsoft365DSC/DSCResources/MSFT_SPOBrowserIdleSignout/MSFT_SPOBrowserIdleSignout.psm1
> +    Confirm-M365DSCDependencies
This still exists

2021-12-07 11:17 UTC, ykuijs commented on Modules/Microsoft365DSC/DSCResources/MSFT_SPOHomeSite/MSFT_SPOHomeSite.psm1
> +    Confirm-M365DSCDependencies
This still exists

2021-12-07 11:17 UTC, ykuijs commented on Modules/Microsoft365DSC/DSCResources/MSFT_SPOHubSite/MSFT_SPOHubSite.psm1
> +    Confirm-M365DSCDependencies
This still exists

2021-12-07 11:17 UTC, ykuijs commented on Modules/Microsoft365DSC/DSCResources/MSFT_SPOOrgAssetsLibrary/MSFT_SPOOrgAssetsLibrary.psm1
> +    Confirm-M365DSCDependencies
This still exists

2021-12-07 11:17 UTC, ykuijs commented on Modules/Microsoft365DSC/DSCResources/MSFT_SPOPropertyBag/MSFT_SPOPropertyBag.psm1
> +    Confirm-M365DSCDependencies
This still exists

2021-12-07 11:17 UTC, ykuijs commented on Modules/Microsoft365DSC/DSCResources/MSFT_SPOSearchManagedProperty/MSFT_SPOSearchManagedProperty.psm1
> +    Confirm-M365DSCDependencies
This still exists

2021-12-07 11:17 UTC, ykuijs commented on Modules/Microsoft365DSC/DSCResources/MSFT_SPOSearchResultSource/MSFT_SPOSearchResultSource.psm1
> +    Confirm-M365DSCDependencies
This still exists

2021-12-07 11:17 UTC, ykuijs commented on Modules/Microsoft365DSC/DSCResources/MSFT_SPOSharingSettings/MSFT_SPOSharingSettings.psm1
> +    Confirm-M365DSCDependencies
This still exists

2021-12-07 11:17 UTC, ykuijs commented on Modules/Microsoft365DSC/DSCResources/MSFT_SPOSite/MSFT_SPOSite.psm1
> +    Confirm-M365DSCDependencies
This still exists

2021-12-07 11:17 UTC, ykuijs commented on Modules/Microsoft365DSC/DSCResources/MSFT_SPOSiteAuditSettings/MSFT_SPOSiteAuditSettings.psm1
> +    Confirm-M365DSCDependencies
This still exists

2021-12-07 11:17 UTC, ykuijs commented on Modules/Microsoft365DSC/DSCResources/MSFT_SPOSiteAuditSettings/MSFT_SPOSiteAuditSettings.psm1
> +    Confirm-M365DSCDependencies
This still exists

2021-12-07 11:17 UTC, ykuijs commented on Modules/Microsoft365DSC/DSCResources/MSFT_SPOSiteDesign/MSFT_SPOSiteDesign.psm1
> +    Confirm-M365DSCDependencies
This still exists

2021-12-07 11:17 UTC, ykuijs commented on Modules/Microsoft365DSC/DSCResources/MSFT_SPOSiteDesignRights/MSFT_SPOSiteDesignRights.psm1
> +    Confirm-M365DSCDependencies
This still exists

2021-12-07 11:17 UTC, ykuijs commented on Modules/Microsoft365DSC/DSCResources/MSFT_SPOSiteScript/MSFT_SPOSiteScript.psm1
> +    Confirm-M365DSCDependencies
This still exists

2021-12-07 11:17 UTC, ykuijs commented on Modules/Microsoft365DSC/DSCResources/MSFT_SPOStorageEntity/MSFT_SPOStorageEntity.psm1
> +    Confirm-M365DSCDependencies
This still exists

2021-12-07 14:39 UTC, NikCharlebois commented
Weird, I originally did not see these comments. Everything should be aligned now. Thanks

2021-12-07 20:33 UTC, ykuijs approved these changes

2021-12-08 11:45 UTC, merged