EXOMailboxPlan: Add resource
microsoft/Microsoft365DSC pull request #1784
Opened 2022-02-24 12:36 UTC by malauter

#### Pull Request (PR) description
Add new resource EXOMailboxPlan

#### This Pull Request (PR) fixes the following issues
-Fixes #1455

2022-03-02 14:30 UTC, NikCharlebois requested changes
Just a small typo in the readme.md file

2022-03-02 14:30 UTC, NikCharlebois commented on Modules/Microsoft365DSC/DSCResources/MSFT_EXOMailboxPlan/readme.md
> +Use this recourse to modify the settings of mailbox plans in the cloud-based service.
Typo in 'resource'

2022-03-02 14:34 UTC, malauter commented on Modules/Microsoft365DSC/DSCResources/MSFT_EXOMailboxPlan/readme.md
> +Use this recourse to modify the settings of mailbox plans in the cloud-based service.
fixed

2022-03-08 13:45 UTC, NikCharlebois approved these changes

2022-03-08 13:45 UTC, merged