Asser-M365DSCBlueprint: add additional Auth Meth to Asser-M365DSCBlueprint
microsoft/Microsoft365DSC pull request #1792
Opened 2022-03-01 09:08 UTC by Timsto

#### Pull Request (PR) description

#### This Pull Request (PR) fixes the following issues

2022-03-08 10:39 UTC, ykuijs requested changes
Could you please also update the changelog to reflect this change?

2022-03-08 10:40 UTC, ykuijs commented
@NikCharlebois Can you please also check this PR? Not 100% if this will work for this function.

2022-03-08 12:30 UTC, NikCharlebois commented
@Timsto This function should not handle credentials. It is purely meant to retrieve the domain if service principal if passed. If credentials are used, then determining the domain is very easy and straightforward:

$domain = $credentials.UserName.Split('@')[1]

2022-07-28 07:29 UTC, andikrueger commented
@NikCharlebois  and @Timsto Are there any updates to this PR? 

At the moment there are two tasks open:

- [ ] Update Changelog
- [ ] Remove `Credential` parameter from `Get-M365DSCTenantDomain`

2022-07-28 07:30 UTC, andikrueger commented on Modules/Microsoft365DSC/Modules/M365DSCUtil.psm1
> +
as mentioned in https://github.com/microsoft/Microsoft365DSC/pull/1792#issuecomment-1061727808 this function should not handle any Credentials.

2022-12-16 16:18 UTC, NikCharlebois commented
@Timsto have you had a chance to look at the comments? Should we keep this PR open or close it?

2023-03-03 15:31 UTC, ykuijs commented
Closing this PR due to inactivity, but code will be adopted in a different PR I am working on.

2023-03-03 15:31 UTC, closed without merging