PR IntuneDeviceConfigurationPolicyAndroidDeviceAdministrator: Initial release
microsoft/Microsoft365DSC pull request #2162
Opened 2022-07-29 19:49 UTC by William-Francillette

#### Pull Request (PR) description

Resource for Intune policy: 
Android Device Administrator device restriction policies

#### This Pull Request (PR) fixes the following issues

2022-08-03 08:58 UTC, andikrueger commented
Could you update the change log with the changes you made?

2022-08-22 16:55 UTC, NikCharlebois requested changes

2022-08-22 16:55 UTC, NikCharlebois commented on Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyAndroidDeviceAdministrator/MSFT_IntuneDeviceConfigurationPolicyAndroidDeviceAdministrator.psm1
> +        Write-Verbose -Message "Reloading1"
Can we make sure to remove this testing verbose?

2022-08-22 16:55 UTC, NikCharlebois commented on Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyAndroidDeviceAdministrator/MSFT_IntuneDeviceConfigurationPolicyAndroidDeviceAdministrator.schema.mof
> +    [Write, Description("")] String Id;
Please provide description for the 3 parameters

2022-08-22 16:55 UTC, NikCharlebois commented on Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyAndroidDeviceAdministrator/MSFT_IntuneDeviceConfigurationPolicyAndroidDeviceAdministrator.schema.mof
> +    [Write, Description("Require encryption on device. Not all devices support encryption.<br>
Can we please make the description on one line and remove the HTML tags even if that may make it harder to read? Thanks

2022-08-23 18:49 UTC, William-Francillette commented
@NikCharlebois  Same as IntuneDeviceConfigurationPolicyAndroidOpenSourceProject
Unit test pass in local
![image](https://user-images.githubusercontent.com/79221284/186239528-f91048d0-f95f-43f2-8ba6-d940c21920f7.png)

But fails in dev due to O365User
![image](https://user-images.githubusercontent.com/79221284/186239683-ed0e766c-aded-48d7-bb61-36516cd5e240.png)

2022-08-25 16:36 UTC, merged