Update MSFT_IntuneAppProtectionPolicyiOS.psm1 - fixes #2942
microsoft/Microsoft365DSC pull request #2944
Opened 2023-02-27 15:22 UTC by menswearUK

added New-M365DSCConnection command to address #2942 - added formatting to current/target values output

#### Pull Request (PR) description

This PR adds a line:
$ConnectionMode = New-M365DSCConnection -Workload 'MicrosoftGraph' -ProfileName beta `
    -InboundParameters $PSBoundParameters

to the Test-TargetResource function of IntuneAppProtectionPolicyiOS

It prevents the Get-TargetResource function returning objects with missing values.  It's not clear to me why the same line in get-TargetResource doesn't work correctly but without this line added here the object returned from the MS graph command uses the v1.0 profile and is missing a number of values which are required for the returned array.  This leads to failed comparisons with config documents even when the settings are correct.

The error and the fix can be seen in a verbose output of start-DSCConfiguration or in test-DSCConfiguration

#### This Pull Request (PR) fixes the following issues

Fixes #2942

2023-02-28 08:23 UTC, ykuijs commented
Even though this solution works, it is more like a workaround. I rather try to solve the underlying issue before implementing a workaround.

2023-03-03 14:59 UTC, menswearUK commented
I thought it was easiest to update this PR with the places I added code into New-M365DscConnection - since the PR is on hold and, once we reach a solution, I can amend further as necessary.
In addition to my initial suggestion I also added a check that the New-M365DscConnection was for MSGraph before applying the switch as it could be used for multiple connections.
In my testing there was no requirement to add further verbose settings changes if the command is run within New-M365DscConnection but I can add those in too if they are required

2023-03-06 16:45 UTC, menswearUK commented
@ykuijs  - I've updated this PR with the fixes discussed in the issue chat - the only thing I've not done is added in the changes to the verbose output (it only seems to be an issue when the profile switch is in the configuration, it doesn't seem to be required in this function although I can add those lines in if you'd prefer).

2023-03-07 07:40 UTC, ykuijs requested changes
Thanks for this update. Just a few minor comments.

2023-03-07 07:40 UTC, ykuijs commented on CHANGELOG.md
> +* New-M365DSCConnection in M365DSCUtil.psm1
Can you please move this item under the MISC section (currently on line 14)

2023-03-07 07:40 UTC, ykuijs commented on Modules/Microsoft365DSC/DSCResources/MSFT_IntuneAppProtectionPolicyiOS/MSFT_IntuneAppProtectionPolicyiOS.psm1
> +    Write-Verbose -Message "Current Values: $((Convert-M365DscHashtableToString -Hashtable $CurrentValues) -replace ';', "`r`n")"
Can you leave this as it was? I like the change, but now it is only implemented for this resource and not for all other resources. I rather change the Convert-M365DscHashtableToString function to do this, so all resources replace the semi colon with an enter.

Please create an issue for this so we can assess the impact and implement separately.

2023-03-07 07:40 UTC, ykuijs commented on Modules/Microsoft365DSC/Modules/M365DSCUtil.psm1
> +                select-mgprofile -Name $profilename
Could you update the cmdlet to match the default PascalCase format: Select-MgProfile

And update the variable name to match the earlier used PascalCasing: $ProfileName

Both are true for all instances you have added.

2023-03-07 07:58 UTC, menswearUK commented
@ykuijs No worries, I've corrected those values now.

2023-03-07 08:00 UTC, ykuijs commented
@menswearUK, thanks for that. But what about the other two comments?

2023-03-09 10:41 UTC, ykuijs approved these changes
LGTM

2023-03-09 11:09 UTC, ykuijs commented
@menswearUK, wanted to merge it, so I could include it in this weeks release. But unfortunately I was unable to. Could you update the PR with the Dev branch?

2023-03-09 11:57 UTC, closed without merging

2023-03-09 13:13 UTC, menswearUK commented
@ykuijs - apologies for this, I was attempting to clear the conflicts and messed it up - I ended up clearing the commits and syncing and it closed the PR with no changes.  I've created a new branch with the updates which has no conflicts and I've put in  a new PR for that.