Remove Az PowerShell dependencies
microsoft/Microsoft365DSC pull request #3375
Opened 2023-06-09 15:36 UTC by NikCharlebois

#### Pull Request (PR) description
* Removing all Az.Accounts dependancies in the module

#### This Pull Request (PR) fixes the following issues
* N/A

2023-06-09 15:37 UTC, NikCharlebois commented
@andikrueger & @ykuijs would appreciate your review on this one. Removing dependency on Az.Accounts in favor of Microsoft.Graph.Application

2023-06-12 07:33 UTC, ykuijs requested changes
Two small comments

2023-06-12 07:33 UTC, ykuijs commented on Modules/Microsoft365DSC/Modules/M365DSCPermissions.psm1
>          return
This section can be removed since we are no longer using Az.Resources

2023-06-12 07:33 UTC, ykuijs commented on Modules/Microsoft365DSC/Modules/M365DSCPermissions.psm1
> -
Shouldn't we include some authentication to the Graph befor calling the Get-MgServicePrincipal cmdlet?

2023-06-12 08:11 UTC, William-Francillette commented
Should the Az.Accounts not be part of MSCloudLoginAssistant dependencies as the Azure workload for example uses Connect-AzAccount?
![image](https://github.com/microsoft/Microsoft365DSC/assets/79221284/cf7ffe54-2876-428f-8c9b-838b165813fe)

2023-06-12 08:28 UTC, andikrueger commented
Non of the supported workloads is part of the manifest. This is due to the critical load times of all the modules...

2023-06-12 08:31 UTC, William-Francillette commented
Oh I see, thanks for the clarification @andikrueger

2023-06-12 13:42 UTC, NikCharlebois commented
The Azure workload is never used as part of M365DSC so we should be good on that front.

2023-06-13 18:52 UTC, NikCharlebois commented
@ykuijs are we good to merge in tomorrow's release? Thanks

2023-06-14 21:16 UTC, ykuijs approved these changes
lgtm

2023-06-14 21:16 UTC, merged