Fix/teams compliance recording policy
microsoft/Microsoft365DSC pull request #3754
Opened 2023-10-04 17:47 UTC by sandrola

#### Pull Request (PR) description
Add CIM Instance to  MSFT_TeamsComplianceRecordingPolicy to be able to compare with configured policy

#### This Pull Request (PR) fixes the following issues
    - Fixes #3712

2023-11-10 14:59 UTC, ykuijs requested changes, later dismissed
Few small comments

2023-11-10 14:59 UTC, ykuijs commented on CHANGELOG.md
> +* TeamsComplianceREcordingPolicy
Could you update your branch with Dev and then place this item alphabetically on the right place? Just the MISC and DEPENDENCIES ones should be at the bottom, the rest alphabetically.

2023-11-10 14:59 UTC, ykuijs commented on Modules/Microsoft365DSC/DSCResources/MSFT_TeamsComplianceRecordingPolicy/MSFT_TeamsComplianceRecordingPolicy.psm1
> +        if($ComplianceRecordingApplications.Count -gt 0){
Please adhere to the code styling conventions: Add a space after the keywords (if/else/foreach) and place the opening brace on a new line.

2023-11-16 11:26 UTC, andikrueger commented
@sandrola Thanks for your PR and the work you put into it! Any chance you could resolve conflicts and address Yorick's comments?

2023-11-16 12:46 UTC, pkernevez commented
As the original issue #3754  has been closed, I think this PR should be close

2023-11-17 08:41 UTC, andikrueger reviewed
Just one minor remark and a question for @NikCharlebois

2023-11-17 08:43 UTC, andikrueger commented on CHANGELOG.md
> +* TeamsComplianceREcordingPolicy
Minor typo REcording

2024-03-18 16:18 UTC, NikCharlebois approved these changes

2024-03-18 16:21 UTC, NikCharlebois commented
Can we please merge and update the PR with the latest changes? Thanks

2024-09-30 11:20 UTC, FabienTschanz commented
@sandrola Could you please update or close the PR? Thank you.

2024-09-30 15:56 UTC, NikCharlebois commented
As we approach our next Major release (Oct 2nd), we need to make confirm this is still a valid PR and update it to resolve any merge conflicts.

2024-10-01 07:12 UTC, sandrola commented
The PR is still valid and I just updated it with dev.

2024-10-02 12:16 UTC, NikCharlebois approved these changes

2024-10-02 12:17 UTC, merged