EXOMailbox Initial release
microsoft/Microsoft365DSC pull request #3877
Opened 2023-11-09 17:18 UTC by levesquesamuel

#### Pull Request (PR) description
EXOMailbox Initial release

2023-11-10 14:44 UTC, NikCharlebois requested changes

2023-11-10 14:44 UTC, NikCharlebois commented on Modules/Microsoft365DSC/DSCResources/MSFT_EXOMailbox/MSFT_EXOMailbox.schema.mof
> +    [Write, Description("")] String RecipientType;
We would need the description for all parameters.

2023-11-10 14:44 UTC, NikCharlebois commented on Modules/Microsoft365DSC/DSCResources/MSFT_EXOMailbox/MSFT_EXOMailbox.schema.mof
> +    [Write, Description("")] String Guid;
If this is only read-only, let's not include it. Also, what is the difference between id and GUID?

2023-11-10 14:44 UTC, NikCharlebois commented on Modules/Microsoft365DSC/DSCResources/MSFT_EXOMailbox/MSFT_EXOMailbox.schema.mof
> +
Remove empty line in schema.

2023-11-10 14:44 UTC, NikCharlebois commented on Modules/Microsoft365DSC/Examples/Resources/EXOMailbox/1-ConfigureMailbox.ps1
> +            AcceptMessagesOnlyFrom                 = "";
Let's remove empty string parameters completely

2023-11-28 11:41 UTC, ykuijs commented
@levesquesamuel Could you please resolve the review comments? After that we can merge your PR.

2023-11-28 11:41 UTC, ykuijs commented
And please update your branch with Dev. It currently has conflicts.

2024-02-26 19:55 UTC, closed without merging