EXOMailContact: Added support for Custom Attributes and Extension Custom Attributes
microsoft/Microsoft365DSC pull request #4103
Opened 2023-12-30 12:59 UTC by raandree

#### Pull Request (PR) description
EXOMailContact: Added support for Custom Attributes and Extension Custom Attributes.

Additionally added the function `Sync-Parameter` which makes splatting much easier.

#### This Pull Request (PR) fixes the following issues
None

2024-01-05 09:01 UTC, ykuijs requested changes
One small comment

2024-01-06 09:52 UTC, raandree commented
@ykuijs, how do I update the changelog as there is no 'unreleased' section? How do I know which version is going to get the PR's changes added?

2024-01-06 09:55 UTC, ykuijs commented
If you sync with Dev, there should be an Unreleased header. Else you can always add an Unreleased section at the top.

2024-01-10 14:41 UTC, NikCharlebois approved these changes

2024-01-10 14:41 UTC, merged