Only do one request instead of n+1 when exporting TeamsCallQueue
microsoft/Microsoft365DSC pull request #4195
Opened 2024-01-19 13:37 UTC by pkernevez

#### Pull Request (PR) description
Only do one request instead of n+1 when exporting TeamsCallQueue
This is not specific at this resource, but this PR only fix it for it.

#### This Pull Request (PR) fixes the following issues
Fixes and Close #4192

2024-01-22 12:28 UTC, NikCharlebois commented
Sorry, I am having a hard time understanding how this is different than what we had previsouly?

2024-01-22 13:40 UTC, ricmestre commented
@nikcharlebois Currently this resource is calling *Get-CsCallQueue*, during *Export-TargetResource*, which gets all call queues, then it iterates per each one of them and calls *Get-CsCallQueue* again inside *Get-TargetResource* although this time with a filter by name to figure out its settings.

It seems what @pkernevez is trying to do here is to keep the initial call to *Get-CsCallQueue* for exporting all queues but avoiding the subsequent calls inside *Get-TargetResource*, in fact bypassing getting inside the Get completely, and just return the settings through the cmdlet *Convert-Resource* he introduced.

Didn't test it tough, don't have any tenants with examples right now.

2024-01-22 13:59 UTC, andikrueger requested changes
This looks like a good runtime improvement for exporting all instances of this resource. The redundant calls to Get-TargetResource are mitigated this way. It even would allow the implementation of $Filter for this resource, if I see it correctly.

2024-01-22 13:59 UTC, andikrueger commented on Modules/Microsoft365DSC/DSCResources/MSFT_TeamsCallQueue/MSFT_TeamsCallQueue.psm1
> +            # $Results = Get-TargetResource @Params
Could you please remove this line.

2024-01-22 15:44 UTC, NikCharlebois commented
Looks like the caching pattern that is being used across most resources, where we cache all instances in the $Script:exportedInstances variable is not fully implemented here. I would rather make sure we keep the patterns aligned across resources than creating yet a new one. Have a look at how we are doing it for the AADUser resource for example:

https://github.com/microsoft/Microsoft365DSC/blob/Dev/Modules/Microsoft365DSC/DSCResources/MSFT_AADUser/MSFT_AADUser.psm1#L184

2024-01-25 08:53 UTC, pkernevez commented
I didn't knew this existing pattern ( I didn't found it before when reading the code).
My target (reducing the number of calls) could be archived by following it, so I'm going to push a new version following it.

2024-01-25 11:47 UTC, pkernevez commented
I revert previous changes and use the export cache pattern, it was partially in place : the cache existed but was not used.

2024-01-29 18:29 UTC, pkernevez commented
Are the changes ok for you  ?

2024-02-26 20:43 UTC, andikrueger approved these changes
LGTM

2024-02-26 20:57 UTC, merged