Add check if NewUnifiedGroupWritebackDefault can be set for Azure Gov
microsoft/Microsoft365DSC pull request #5305
Opened 2024-10-30 18:04 UTC by mpoulson

#### Pull Request (PR) description
Add check if NewUnifiedGroupWritebackDefault  exists before trying to pull it as this does not always exist in Azure Gov

#### This Pull Request (PR) fixes the following issues
-Fixes #5213

2024-10-31 19:25 UTC, FabienTschanz commented on Modules/Microsoft365DSC/DSCResources/MSFT_AADGroupsSettings/MSFT_AADGroupsSettings.psm1
> +            if (-not [System.String]::IsNulorEmpty($valueNewUnifiedGroupWritebackDefault.Value))
```suggestion
            if (-not [System.String]::IsNullOrEmpty($valueNewUnifiedGroupWritebackDefault.Value))
```

2024-11-01 05:33 UTC, FabienTschanz reviewed
Changelog entry missing, otherwise looks good to go.

2024-11-01 11:01 UTC, NikCharlebois requested changes
Missing an entry in the changelog

2024-11-05 14:54 UTC, NikCharlebois approved these changes

2024-11-05 14:54 UTC, merged