MSFT_AADTenantDetails : Initial Release
microsoft/Microsoft365DSC pull request #781
Opened 2020-09-15 15:24 UTC by Timsto

#### Pull Request (PR) description

    MSFT_AADTenantDetails : Initial Release

#### This Pull Request (PR) fixes the following issues

  - Fixes #493

2020-09-15 15:57 UTC, NikCharlebois requested changes
Few comments to review. Also missing example and Unit Tests

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-:-MHHTwNL8csLPOasvdMV:b58xhuv)* status: all files reviewed, 15 unresolved discussions (waiting on @Timsto)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1, line 1 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHHT6ep4cbuWS7d6Znr:-MHHT6ep4cbuWS7d6Zns:b-5d8up6) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/bca45653b9705cc00a6b58742f0f04587dffe339/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L1)):*
> ```PowerShell
> function Get-TargetResource {
> ```

{ needs to be on a separate line
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1, line 24 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHHRm_92yEbIpD8AaiN:-MHHRm_92yEbIpD8AaiO:bx1fa8) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/bca45653b9705cc00a6b58742f0f04587dffe339/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L24)):*
> ```PowerShell
>         [Parameter(Mandatory = $true)]
>         [System.String]
>         $isSingleInstance,
> ```

For consistency, please have this appear as the first parameter at the top of the list, and use a capital 'I'
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1, line 28 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHHRsGf-Z68E9VE3Nq6:-MHHRsGf-Z68E9VE3Nq7:b52mh0b) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/bca45653b9705cc00a6b58742f0f04587dffe339/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L28)):*
> ```PowerShell
>         [Parameter()]
>         [System.Management.Automation.PSCredential]
>         $GlobalAdminAccount
> ```

AAD resources also need to allow authenticating using CBA. We need to add

        [Parameter()]
        [System.String]
        $ApplicationId,

        [Parameter()]
        [System.String]
        $TenantId,

        [Parameter()]
        [System.String]
        $CertificateThumbprint

To the methods, and in the meta.mof. Refer to other AAD resources for examples.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1, line 54 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHHSKaG98t2qDEzTpAz:-MHHSKaG98t2qDEzTpB-:brs8gyi) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/bca45653b9705cc00a6b58742f0f04587dffe339/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L54)):*
> ```PowerShell
>     }
>     catch {
>         Write-Verbose -Message "Could not retriueve AzureAD Tenant Details"
> ```

Typo in retrieve.
Also, I would recommend we throw out an error if the Tenant Details can't be retrieved and get rid of $nullReturn since an empty return value doesn't make sense for this resource.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1, line 59 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHHSYVH-sb6UhSTenxA:-MHHSYVH-sb6UhSTenxB:bcywyof) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/bca45653b9705cc00a6b58742f0f04587dffe339/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L59)):*
> ```PowerShell
> 
>     $result = @{
>         TenantName                              = $AADTenantDetails.DisplayName
> ```

TenantName is not a property of the Get-TargetResource. Should it be, and if so, should it be the primary key instead of IsSingleInstance? Can the same account be able to set tenant Details for multiple tenants? 
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1, line 69 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHHT43_CbsrtLU7PA_m:-MHHT43_CbsrtLU7PA_n:b-5d8up6) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/bca45653b9705cc00a6b58742f0f04587dffe339/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L69)):*
> ```PowerShell
> }
> 
> function Set-TargetResource {
> ```

{ needs to be on a separate line
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1, line 91 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHHSu-45YnZAOu8cDYZ:-MHHSu-45YnZAOu8cDY_:b-ya81ng) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/bca45653b9705cc00a6b58742f0f04587dffe339/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L91)):*
> ```PowerShell
>         [Parameter(Mandatory = $true)]
>         [System.String]
>         $isSingleInstance,
> ```

Same as above
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1, line 123 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHHT2-e2zMSmtibBQDW:-MHHT2-e2zMSmtibBQDX:b-5d8up6) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/bca45653b9705cc00a6b58742f0f04587dffe339/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L123)):*
> ```PowerShell
> }
> 
> function Test-TargetResource  {
> ```

{ needs to be on a separate line
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1, line 146 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHHT1-34G4OOsVjXKHs:-MHHT1-34G4OOsVjXKHt:b-ya81ng) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/bca45653b9705cc00a6b58742f0f04587dffe339/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L146)):*
> ```PowerShell
>         [Parameter(Mandatory = $true)]
>         [System.String]
>         $isSingleInstance,
> ```

Same as above
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1, line 162 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHHTFdt3UvZd86gCF91:-MHHTFdt3UvZd86gCF92:bn0zuv0) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/bca45653b9705cc00a6b58742f0f04587dffe339/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L162)):*
> ```PowerShell
>     #endregion
> 
>     Write-Verbose -Message "Testing configuration of AzureAD Tenant Details"
> ```

For consistency, all other verbose outputs have Azure AD spelled in two word. I suggest spelling it with just one word and update the other entries instead.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1, line 193 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHHTPuY8SBWBph-e1Z-:-MHHTPuY8SBWBph-e1Z0:b-ptiobd) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/bca45653b9705cc00a6b58742f0f04587dffe339/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L193)):*
> ```PowerShell
>         [Parameter()]
>         [System.String]
>         $SecurityComplianceNotificationMails,
> ```

Only mandatory parameters are required for the Export-TargetResource method. Please refer to other AAD resources for example.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1, line 227 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHHTawu5VH4-FkvbdLc:-MHHTawv3SraMbymrEhQ:b-rhkvsp) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/bca45653b9705cc00a6b58742f0f04587dffe339/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L227)):*
> ```PowerShell
> 
>     $Params = @{
>         TenantName                              = $AADTenantDetails.DisplayName
> ```

This will fail since that property is not accepted on the Get-TargetResource.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_A [...]

2020-09-15 18:24 UTC, Timsto reviewed
Done.

> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-:-MHI-1f2Dn4qWeiVZkje:b-896fix)* status: all files reviewed, 15 unresolved discussions (waiting on @NikCharlebois)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1, line 1 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHHT6ep4cbuWS7d6Znr:-MHHjOGa1G1KYjZz99Qy:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/bca45653b9705cc00a6b58742f0f04587dffe339/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L1)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

{ needs to be on a separate line
</blockquote></details>

Done.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1, line 24 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHHRm_92yEbIpD8AaiN:-MHHjWSw7SGssi88TXOh:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/bca45653b9705cc00a6b58742f0f04587dffe339/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L24)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

For consistency, please have this appear as the first parameter at the top of the list, and use a capital 'I'
</blockquote></details>

Done.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1, line 28 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHHRsGf-Z68E9VE3Nq6:-MHHjj0I8NB_3JVAtXI4:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/bca45653b9705cc00a6b58742f0f04587dffe339/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L28)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

AAD resources also need to allow authenticating using CBA. We need to add

        [Parameter()]
        [System.String]
        $ApplicationId,

        [Parameter()]
        [System.String]
        $TenantId,

        [Parameter()]
        [System.String]
        $CertificateThumbprint

To the methods, and in the meta.mof. Refer to other AAD resources for examples.
</blockquote></details>

Done.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1, line 54 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHHSKaG98t2qDEzTpAz:-MHI-NF4E-4bOUo530jy:b-nxt0v4) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/bca45653b9705cc00a6b58742f0f04587dffe339/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L54)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Typo in retrieve.
Also, I would recommend we throw out an error if the Tenant Details can't be retrieved and get rid of $nullReturn since an empty return value doesn't make sense for this resource.
</blockquote></details>

Verbose Actions told enough maybe? 
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1, line 59 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHHSYVH-sb6UhSTenxA:-MHHkVMXCgN8Fs7PCdl9:b5o8z9c) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/bca45653b9705cc00a6b58742f0f04587dffe339/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L59)):*
> TenantName is not a property of the Get-TargetResource. Should it be, and if so, should it be the primary key instead of IsSingleInstance? Can the same account be able to set tenant Details for multiple tenants?
Removed because it makes no sense.  Was just an idea for an output.  
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1, line 69 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHHT43_CbsrtLU7PA_m:-MHHlHI13W7fh4HGZfaw:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/bca45653b9705cc00a6b58742f0f04587dffe339/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L69)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

{ needs to be on a separate line
</blockquote></details>

Done.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1, line 91 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHHSu-45YnZAOu8cDYZ:-MHHlGpN1bOgJQAyWZ2M:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/bca45653b9705cc00a6b58742f0f04587dffe339/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L91)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1, line 123 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHHT2-e2zMSmtibBQDW:-MHHlFwO3WzPKzOdU8a1:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/bca45653b9705cc00a6b58742f0f04587dffe339/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L123)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

{ needs to be on a separate line
</blockquote></details>

Done.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1, line 146 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHHT1-34G4OOsVjXKHs:-MHHlFS24Q7L4NXvb6jY:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/bca45653b9705cc00a6b58742f0f04587dffe339/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L146)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1, line 162 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHHTFdt3UvZd86gCF91:-MHHlEwMA4obHT24ncOL:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/bca45653b9705cc00a6b58742f0f04587dffe339/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L162)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

For consistency, all other verbose outputs have Azure AD spelled in two word. I suggest spelling it with just one word and update the other entries instead.
</blockquote></details>

Done.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1, line 193 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHHTPuY8SBWBph-e1Z-:-MHHmQLgCLw49OYw43-y:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/bca45653b9705cc00a6b58742f0f04587dffe339/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L193)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Only mandatory parameters are required for the Export-TargetResource method. Please refer to other AAD resources for example.
</blockquote></details>

Done.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1, line 227 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHHTawu5VH4-FkvbdLc:-MHHmaZwEXdG7-GTBkEe:b-896fix) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/bca45653b9705cc00a6b58742f0f04587dffe339/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L227)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>
 [...]

2020-09-15 20:26 UTC, NikCharlebois requested changes
Additional comments and suggested fixes for unit tests

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-:-MHIRUN63An3MIFTDw9X:bx1c1uf)* status: all files reviewed, 7 unresolved discussions (waiting on @Timsto)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1, line 54 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHHSKaG98t2qDEzTpAz:-MHIPaGx-p97f9YC5XJc:b-xz043f) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/bca45653b9705cc00a6b58742f0f04587dffe339/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L54)):*
<details><summary><i>Previously, Timsto (timsto) wrote…</i></summary><blockquote>

Verbose Actions told enough maybe? 
</blockquote></details>

No, since  this would also throw out a positive configuration drift. We should really throw an error out if it fails.

Also make sure to fix the typo in 'retrieve'
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1, line 193 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHHTPuY8SBWBph-e1Z-:-MHIPvy41-SUDMYkeYCP:bwn5kji) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/bca45653b9705cc00a6b58742f0f04587dffe339/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L193)):*
<details><summary><i>Previously, Timsto (timsto) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I am still seeing all optional parameters listed. Please remove MarketingNotificationEmails, SecurityComplianceNotificationMails, etc from the signature of the Export-TargetResource function.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/readme.md, line 12 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHHTr9X1zbw4LFl6MOM:-MHIQHuB8pvc5RLkXbd7:bt724ol) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/bca45653b9705cc00a6b58742f0f04587dffe339/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/readme.md#L12)):*
<details><summary><i>Previously, Timsto (timsto) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Meaning there are no permissions required?
___
*[Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADTenantDetails.Tests.ps1, line 24 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHIQhYv05LxJtFFmcW6:-MHIQhYv05LxJtFFmcW7:bb8dxxn) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/81b2fec7a26a2399ccdc7d594f984e5820f30a38/Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADTenantDetails.Tests.ps1#L24)):*
> ```PowerShell
>         BeforeAll {
>             $secpasswd = ConvertTo-SecureString "test@password1" -AsPlainText -Force
>             $GlobalAdminAccount = New-Object System.Management.Automation.PSCredential ("tenantadmin", $secpasswd)
> ```

Username needs to be in form of <name>@<domain.onmicrosoft.com>
___
*[Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADTenantDetails.Tests.ps1, line 63 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHIQmCl5xn6YZzC_Pdg:-MHIQmCl5xn6YZzC_Pdh:b-e2os7j) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/81b2fec7a26a2399ccdc7d594f984e5820f30a38/Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADTenantDetails.Tests.ps1#L63)):*
> ```PowerShell
>                     SecurityComplianceNotificationMails    = "exapmle@contoso.com"
>                     MarketingNotificationEmails            = "exapmle@contoso.com"
>                     GlobalAdminAccount                     = $GlobalAdmin
> ```

This variable is actually named $GlobalAdminAccount in your file, not $GlobalAdmin. All contexts are exhibiting the same issue.
___
*[Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADTenantDetails.Tests.ps1, line 88 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHIQr4k40Dm6r8BYdBq:-MHIQr4k40Dm6r8BYdBr:b-ya81ng) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/81b2fec7a26a2399ccdc7d594f984e5820f30a38/Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADTenantDetails.Tests.ps1#L88)):*
> ```PowerShell
>                     SecurityComplianceNotificationMails    = "exapmle@contoso.com"
>                     MarketingNotificationEmails            = "exapmle@contoso.com"
>                     GlobalAdminAccount                     = $GlobalAdmin
> ```

Same as above
___
*[Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADTenantDetails.Tests.ps1, line 92 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHIQvHJAUG0Bpf35r-c:-MHIQvHJAUG0Bpf35r-d:b-i4nwnb) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/81b2fec7a26a2399ccdc7d594f984e5820f30a38/Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADTenantDetails.Tests.ps1#L92)):*
> ```PowerShell
>                 }
> 
>                 Mock -CommandName New-M365DSCConnection -MockWith {
> ```

This is already mocked at the Global Scope. Remove the duplicate in the specific contexts


<!-- Sent from Reviewable.io -->

2020-09-15 21:00 UTC, Timsto reviewed
Updated in r2 review push

> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-:-MHIZEyIBDwHOFadzeWO:b-pvyf7x)* status: all files reviewed, 7 unresolved discussions (waiting on @NikCharlebois)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1, line 54 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHHSKaG98t2qDEzTpAz:-MHIYcjkCxm5leO4ciaM:b-4iu1n1) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/bca45653b9705cc00a6b58742f0f04587dffe339/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L54)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

No, since  this would also throw out a positive configuration drift. We should really throw an error out if it fails.

Also make sure to fix the typo in 'retrieve'
</blockquote></details>

now added handling error and $NullReturn output
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1, line 193 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHHTPuY8SBWBph-e1Z-:-MHIUEZQ0qiLd3urLJ9C:b-urzu8f) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/bca45653b9705cc00a6b58742f0f04587dffe339/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L193)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

I am still seeing all optional parameters listed. Please remove MarketingNotificationEmails, SecurityComplianceNotificationMails, etc from the signature of the Export-TargetResource function.
</blockquote></details>

now they are removed.  got a problem with codespaces.  
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/readme.md, line 12 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHHTr9X1zbw4LFl6MOM:-MHIUkPO4ncw5C4iYWtB:b9qd4x9) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/bca45653b9705cc00a6b58742f0f04587dffe339/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/readme.md#L12)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Meaning there are no permissions required?
</blockquote></details>

sure. wasnt pushed.   same problem with Codespaces.  
___
*[Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADTenantDetails.Tests.ps1, line 24 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHIQhYv05LxJtFFmcW6:-MHIVbLaDUSR-l2FOUuW:b-jir0rn) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/81b2fec7a26a2399ccdc7d594f984e5820f30a38/Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADTenantDetails.Tests.ps1#L24)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Username needs to be in form of <name>@<domain.onmicrosoft.com>
</blockquote></details>

Took this from another resource.   i will take a look tomorrow from there i get it and updated it. 
___
*[Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADTenantDetails.Tests.ps1, line 63 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHIQmCl5xn6YZzC_Pdg:-MHIWCfbEfRTKf5MhNLi:byxzt2p) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/81b2fec7a26a2399ccdc7d594f984e5820f30a38/Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADTenantDetails.Tests.ps1#L63)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

This variable is actually named $GlobalAdminAccount in your file, not $GlobalAdmin. All contexts are exhibiting the same issue.
</blockquote></details>

fixed to $GlobalAdminAccount
___
*[Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADTenantDetails.Tests.ps1, line 88 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHIQr4k40Dm6r8BYdBq:-MHIWHfP961PYssCzXVh:b-y5hqf1) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/81b2fec7a26a2399ccdc7d594f984e5820f30a38/Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADTenantDetails.Tests.ps1#L88)):*
> fixed to $GlobalAdminAccount
fixed to $GlobalAdminAccount
___
*[Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADTenantDetails.Tests.ps1, line 92 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHIQvHJAUG0Bpf35r-c:-MHIWdHI7sdBofptBFxP:brzvmff) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/81b2fec7a26a2399ccdc7d594f984e5820f30a38/Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADTenantDetails.Tests.ps1#L92)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

This is already mocked at the Global Scope. Remove the duplicate in the specific contexts
</blockquote></details>

Remove it from the contexts


<!-- Sent from Reviewable.io -->

2020-09-15 22:54 UTC, NikCharlebois requested changes
Forgot to mention, please update the ChangeLog with an entry for:

* AADTenantDetails
  * Initial Release (Issue #493)

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-:-MHIwvK3B5X2-Mk9J8tl:bn1aknp)* status: all files reviewed, 3 unresolved discussions (waiting on @Timsto)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1, line 54 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHHSKaG98t2qDEzTpAz:-MHIx4nEC5IfVL9WY0IH:b-pleb69) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/bca45653b9705cc00a6b58742f0f04587dffe339/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L54)):*
<details><summary><i>Previously, Timsto (timsto) wrote…</i></summary><blockquote>

now added handling error and $NullReturn output
</blockquote></details>

The thing is, if AADTenantDetails is null, there was an error somewhere and we should throw an error, returning an empty hashtable is going against the DSC principles in this instance.
___
*[Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADTenantDetails.Tests.ps1, line 24 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHIQhYv05LxJtFFmcW6:-MHIxMvR6IFpZDJ8NFYU:b-k9730g) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/81b2fec7a26a2399ccdc7d594f984e5820f30a38/Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADTenantDetails.Tests.ps1#L24)):*
<details><summary><i>Previously, Timsto (timsto) wrote…</i></summary><blockquote>

Took this from another resource.   i will take a look tomorrow from there i get it and updated it. 
</blockquote></details>

Sorry, the <domain> meant to indicate any domain. We normally use tenantadmin@contoso.onmicrosoft.com. Please remove the <domain> and replace by contoso. Thanks
___
*[Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADTenantDetails.Tests.ps1, line 73 at r3](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHIy25x8qeMHeuiH5ta:-MHIy25x8qeMHeuiH5tb:b-hr2sts) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/ddcc959f8d73c84d674f9075e4bb0d559f0f5dc4/Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADTenantDetails.Tests.ps1#L73)):*
> ```PowerShell
> 
>             It "Should return values from the get method" {
>                 (Get-TargetResource @testParams).Ensure | Should -Be 'Absent'
> ```

The Ensure parameter is not part of the AADTenantDetails, therefore it will never be returned. In your case here, it's not possible to test this Context scenario since we said previously that if we can't get the Tenant Details then we throw an error. 


<!-- Sent from Reviewable.io -->

2020-09-16 11:37 UTC, Timsto reviewed
Units teste failed against at points that i didnt touch. 
There can i set that changelog entry? 

> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-:-MHLgjhj5pwFdBbXrnP7:b-slazzw)* status: all files reviewed, 3 unresolved discussions (waiting on @NikCharlebois)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1, line 54 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHHSKaG98t2qDEzTpAz:-MHLgU7FD3Td_Bgw8ZgP:b-us4pxr) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/bca45653b9705cc00a6b58742f0f04587dffe339/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L54)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

The thing is, if AADTenantDetails is null, there was an error somewhere and we should throw an error, returning an empty hashtable is going against the DSC principles in this instance.
</blockquote></details>

ok build it now the same way like the teamscalling Policy Ressource.  
___
*[Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADTenantDetails.Tests.ps1, line 24 at r2](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHIQhYv05LxJtFFmcW6:-MHLVviWA5emFI6oFWjX:btnmvzw) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/81b2fec7a26a2399ccdc7d594f984e5820f30a38/Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADTenantDetails.Tests.ps1#L24)):*
> tenantadmin@contoso.onmicrosoft.com
ah ok thanks for the info.   fixed it. 
___
*[Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADTenantDetails.Tests.ps1, line 73 at r3](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHIy25x8qeMHeuiH5ta:-MHLZAOnEy1NFR5q7Z_R:bo8wj9e) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/ddcc959f8d73c84d674f9075e4bb0d559f0f5dc4/Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADTenantDetails.Tests.ps1#L73)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

The Ensure parameter is not part of the AADTenantDetails, therefore it will never be returned. In your case here, it's not possible to test this Context scenario since we said previously that if we can't get the Tenant Details then we throw an error. 
</blockquote></details>

Removed it. 


<!-- Sent from Reviewable.io -->

2020-09-16 13:13 UTC, NikCharlebois requested changes
Additional items to review

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-:-MHM27Fu64Eb3Dvdbokj:b35grt)* status: all files reviewed, 3 unresolved discussions (waiting on @Timsto)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1, line 54 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHHSKaG98t2qDEzTpAz:-MHM0VRB8i6e7DygtKIF:bw55xt8) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/bca45653b9705cc00a6b58742f0f04587dffe339/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L54)):*
<details><summary><i>Previously, Timsto (timsto) wrote…</i></summary><blockquote>

ok build it now the same way like the teamscalling Policy Ressource.  
</blockquote></details>

We need to throw an error, not return null. TeamsCallingPolicy is different because it is possible for the instance in question not to exist. In your case, it is impossible for a Tenant not to have settings. The resource should never return $nullReturn, and instead should throw a meaningful error stating that something went wrong trying to retrieve the current Azure AD Tenant Details.
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1, line 238 at r4](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHM1ukOD0hkwzPXavRd:-MHM1ukOD0hkwzPXavRe:bqcve7x) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/401ad001c8fdec6e2fe3386b714e0d6bd3aa2df7/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L238)):*
> ```PowerShell
>         [Parameter(Mandatory = $true)]
>         [System.String]
>         $isSingleInstance,
> ```

This property is not needed for this method. Only the mandatory authentication parameters need to be required.
___
*[Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADTenantDetails.Tests.ps1, line 117 at r4](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHM1HAsC2GZK4YQevLm:-MHM1HAsC2GZK4YQevLn:blp31vc) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/401ad001c8fdec6e2fe3386b714e0d6bd3aa2df7/Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADTenantDetails.Tests.ps1#L117)):*
> ```PowerShell
>                     $AADTenantDetails | Add-Member -MemberType NoteProperty -Name SecurityComplianceNotificationMails -Value "exapmle@contoso.com"
>                     $AADTenantDetails | Add-Member -MemberType NoteProperty -Name SecurityComplianceNotificationPhones -Value "+1123456789"
>                     $AADTenantDetails | Add-Member -MemberType NoteProperty -Name TechnicalNotificationMails -Value "exapmle@contoso.com"
> ```

The method then needs to return the object in question.

You are missing:
return $AADTenantDetails


<!-- Sent from Reviewable.io -->

2020-09-16 14:45 UTC, Timsto reviewed
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/781)* status: all files reviewed, 3 unresolved discussions (waiting on @NikCharlebois)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1, line 54 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHHSKaG98t2qDEzTpAz:-MHMN0Nw9m0SINp_3V-x:b-6jkh1i) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/bca45653b9705cc00a6b58742f0f04587dffe339/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L54)):*
> 401ad00: AADTenantDetails
> Initial Release (Issue #493)
> fixed unit test
hopefully this is fine now..  if not please lets have a sort call 
___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1, line 238 at r4](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHM1ukOD0hkwzPXavRd:-MHM6kdb4e0rqO05ks3K:b5ls4im) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/401ad001c8fdec6e2fe3386b714e0d6bd3aa2df7/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L238)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

This property is not needed for this method. Only the mandatory authentication parameters need to be required.
</blockquote></details>

alright. 
___
*[Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADTenantDetails.Tests.ps1, line 117 at r4](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHM1HAsC2GZK4YQevLm:-MHM77gV9qVpnNa9f_vY:bhnxfob) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/401ad001c8fdec6e2fe3386b714e0d6bd3aa2df7/Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADTenantDetails.Tests.ps1#L117)):*
> return $AADTenantDetails
fixed it also in other mocks. 


<!-- Sent from Reviewable.io -->

2020-09-16 15:20 UTC, NikCharlebois requested changes
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/781)* status: all files reviewed, 2 unresolved discussions (waiting on @Timsto)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1, line 54 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHHSKaG98t2qDEzTpAz:-MHMUxzK1Pf6c3TNgiLJ:b-lr6jvn) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/bca45653b9705cc00a6b58742f0f04587dffe339/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L54)):*
<details><summary><i>Previously, Timsto (timsto) wrote…</i></summary><blockquote>

> 401ad00: AADTenantDetails
> Initial Release (Issue #493)
> fixed unit test
hopefully this is fine now..  if not please lets have a sort call 
</blockquote></details>

Again, we need to throw an error. Returning values here will defeat the purpose of the Export-TargetResource. Tenant Details can't be null unless something went very wrong, in which case we need to let the user know right away.

Instead of returning a value, let's do:

throw "Could not retrieve AzureAD Tenant Details"
___
*[Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADTenantDetails.Tests.ps1, line 80 at r4](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHMUhX66MNdrU_KOaTO:-MHMUhX66MNdrU_KOaTP:bbs7olt) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/401ad001c8fdec6e2fe3386b714e0d6bd3aa2df7/Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADTenantDetails.Tests.ps1#L80)):*
> ```PowerShell
>             BeforeAll {
>                 $testParams = @{
>                     TechnicalNotificationMails             = "exapmle@contoso.com"
> ```

We shouldn't remove those otherwise the tests are not meaningful.


<!-- Sent from Reviewable.io -->

2020-09-16 15:59 UTC, Timsto reviewed
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/781)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @NikCharlebois)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1, line 54 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHHSKaG98t2qDEzTpAz:-MHMXIfoAF4SlyxKBO-g:bz73ei9) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/bca45653b9705cc00a6b58742f0f04587dffe339/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L54)):*
> throw "Could not retrieve AzureAD Tenant Details"
do you mean this? 
if ($null -eq $AADTenantDetails)
    {
        throw "Could not retrieve AzureAD Tenant Details"
    }
___
*[Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADTenantDetails.Tests.ps1, line 80 at r4](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHMUhX66MNdrU_KOaTO:-MHMY7fXEPvTYCPJN7lk:b-j1bz47) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/401ad001c8fdec6e2fe3386b714e0d6bd3aa2df7/Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADTenantDetails.Tests.ps1#L80)):*
> those otherwise the tests are not meaningf
Added those again


<!-- Sent from Reviewable.io -->

2020-09-23 10:19 UTC, NikCharlebois requested changes
Replied to comment. Thanks

> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-:-MHuSYgu7rUgmmmj0Fu0:b-676if3)* status: all files reviewed, 1 unresolved discussion (waiting on @Timsto)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1, line 54 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHHSKaG98t2qDEzTpAz:-MHuSRp32NkWjqauUoFe:b-qpuq3d) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/bca45653b9705cc00a6b58742f0f04587dffe339/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L54)):*
<details><summary><i>Previously, Timsto (timsto) wrote…</i></summary><blockquote>

> throw "Could not retrieve AzureAD Tenant Details"
do you mean this? 
if ($null -eq $AADTenantDetails)
    {
        throw "Could not retrieve AzureAD Tenant Details"
    }
</blockquote></details>

yes, sorry


<!-- Sent from Reviewable.io -->

2020-09-29 12:38 UTC, Timsto reviewed
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/781)* status: all files reviewed, 1 unresolved discussion (waiting on @NikCharlebois)

___
*[Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1, line 54 at r1](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-MHHSKaG98t2qDEzTpAz:-MIOrbhV8BgNhrTglOS8:b-2qlm68) ([raw file](https://github.com/microsoft/microsoft365dsc/blob/bca45653b9705cc00a6b58742f0f04587dffe339/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L54)):*
> 6384e95: AADTenantDetails
> Initial Release (Issue #493)
alright. implemented this


<!-- Sent from Reviewable.io -->

2020-09-29 12:38 UTC, Timsto reviewed
update unit test

> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-:-MIOrf6cC-FZwNWRhkLt:bbb3zmk)* status: all files reviewed, 1 unresolved discussion (waiting on @NikCharlebois)



<!-- Sent from Reviewable.io -->

2020-09-30 10:49 UTC, NikCharlebois approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/microsoft/microsoft365dsc/781#-:-MITb9bE83J5m-GTGpwZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-30 10:51 UTC, merged